spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-246-84-200.eu-west-1.compute.amazonaws.com:5432/d62bieuiq99qos?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: vciowxblnmnnma
    password: a489058d2038caeb4a30346de2e4e091fef51a5031200e7b12118fdee3aef7d1
    tomcat:
      max-active: 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  jackson:
    default-property-inclusion: non_empty
  mvc:
    view:
      suffix: .html

jwt:
  secret: Vc88mvueeo4pEwh2lAee2x64yd8kWan53Az1L1PYBG0F3jRCTa6IBVNyOGEJZErS  # min 32 length
  header: Authorization
  token-prefix: Bearer
  expiration-time: 86400  # 60 * 60 * 24 -> 1 day (in seconds)

cors:
  origins:
    - '*'
  methods:
    - '*'
  headers:
    - X-Requested-With
    - Origin
    - Content-Type
    - Authorization
    - X-Frame-Options

server:
  port: 9000
